jQuery(document).ready(function($) {
	var ssbp_sb_social_selected_theme1 = '<div class="mn-social-bottom-c"> <a href="#" class="mn-social-bottom-facebook-theme1 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme1 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme1 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme1 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme1 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme2 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme2 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme2 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme2 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme2 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme2 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme3 = '<div class="mn-social-bottom-c theme3"> <a href=""  class="mn-social-bottom-facebook-theme3 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme3 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme3 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme3 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme3 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme4 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme4 ssbp_facebook_icon"><i class="fa fa-facebook"></i><span>facebook</span></a> <a href=""  class="mn-social-bottom-twitter-theme4 ssbp_twitter_icon"><i class="fa fa-twitter"></i><span>twitter</span></a> <a href=""  class="mn-social-bottom-linkedin-theme4 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i><span>linkedIn</span></a> <a href=""  class="mn-social-bottom-google-theme4 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i><span>google+</span></a> <a href=""  class="mn-social-bottom-pinterest-theme4 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i><span>pinterest</span></a> </div>';
	var ssbp_sb_social_selected_theme5 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme45 ssbp_facebook_icon"><i class="fa fa-facebook"></i><span>facebook</span></a> <a href=""  class="mn-social-bottom-twitter-theme45 ssbp_twitter_icon"><i class="fa fa-twitter"></i><span>twitter</span></a> <a href=""  class="mn-social-bottom-linkedin-theme45 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i><span>linkedIn</span></a> <a href=""  class="mn-social-bottom-google-theme45 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i><span>google+</span></a> <a href=""  class="mn-social-bottom-pinterest-theme45 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i><span>pinterest</span></a> </div>';
	var ssbp_sb_social_selected_theme6 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme5 ssbp_facebook_icon"><i class="fa fa-facebook"></i><span>facebook</span></a> <a href=""  class="mn-social-bottom-twitter-theme5 ssbp_twitter_icon"><i class="fa fa-twitter"></i><span>twitter</span></a> <a href=""  class="mn-social-bottom-linkedin-theme5 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i><span>LinkedIn</span></a> <a href=""  class="mn-social-bottom-google-theme5 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i><span>google+</span></a> <a href=""  class="mn-social-bottom-pinterest-theme5 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i><span>pinterest</span></a> </div> ';
	var ssbp_sb_social_selected_theme7 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme6 ssbp_facebook_icon"><i class="fa fa-facebook"></i><span>facebook</span></a> <a href=""  class="mn-social-bottom-twitter-theme6 ssbp_twitter_icon"><i class="fa fa-twitter"></i><span>twitter</span></a> <a href=""  class="mn-social-bottom-linkedin-theme6 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i><span>LinkedIn</span></a> <a href=""  class="mn-social-bottom-google-theme6 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i><span>google+</span></a> <a href=""  class="mn-social-bottom-pinterest-theme6 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i><span>pinterest</span></a> </div>';
	var ssbp_sb_social_selected_theme8 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme7 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme7 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme7 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme7 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme7 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme9 = '<div class="mn-social-bottom-c"> <a href=""  class="mn-social-bottom-facebook-theme8 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme8 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme8 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme8 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme8 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme10 = '<div class="ssbp_buttons"> <a  href="#" class="btn facebook ssbp_facebook_icon"> <span class="label">Facebook</span> <span class="icon fa fa-facebook"></span> </a> <a   href="#" class="btn google-plus ssbp_googleplus_icon"> <span class="label">Google+</span> <span class="icon fa fa-google-plus"></span> </a> <a href=""  class="btn twitter ssbp_twitter_icon"> <span class="label">Twitter</span> <span class="icon fa fa-twitter"></span> </a> <a href=""   class="btn linkedin ssbp_linkedin_icon"> <span class="label">Linkedin</span> <span class="icon fa fa-linkedin"></span> </a> <a   href="#" class="btn pinterest ssbp_pinterest_icon"> <span class="label">Pinterest</span> <span class="icon fa fa-pinterest-p"></span> </a> </div> ';
	var ssbp_sb_social_selected_theme11 = '<div class="ssbp_buttons2"> <a href="#" class="btn facebook ssbp_facebook_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-facebook" aria-hidden="true"></i></span> <span class="icon fa fa-facebook"></span> </a> <a href="#" class="btn google-plus ssbp_googleplus_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-google-plus" aria-hidden="true"></i></span> <span class="icon fa fa-google-plus"></span> </a> <a href="#" class="btn twitter ssbp_twitter_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-twitter" aria-hidden="true"></i></span> <span class="icon fa fa-twitter"></span> </a> <a href="#" class="btn linkedin ssbp_linkedin_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-linkedin" aria-hidden="true"></i></span> <span class="icon fa fa-linkedin"></span> </a> <a href="#" class="btn pinterest ssbp_pinterest_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-pinterest-p" aria-hidden="true"></i></span> <span class="icon fa fa-pinterest-p"></span> </a> </div>';
	var ssbp_sb_social_selected_theme12 = '<div class="ssbp_buttons3"> <a href="#" class="btn facebook ssbp_facebook_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-facebook" aria-hidden="true"></i></span> <span class="icon fa fa-facebook"></span> </a> <a href="#" class="btn google-plus ssbp_googleplus_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-google-plus" aria-hidden="true"></i></span> <span class="icon fa fa-google-plus"></span> </a> <a href="#" class="btn twitter ssbp_twitter_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-twitter" aria-hidden="true"></i></span> <span class="icon fa fa-twitter"></span> </a> <a href="#" class="btn linkedin ssbp_linkedin_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-linkedin" aria-hidden="true"></i></span> <span class="icon fa fa-linkedin"></span> </a> <a href="#" class="btn pinterest ssbp_pinterest_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-pinterest-p" aria-hidden="true"></i></span> <span class="icon fa fa-pinterest-p"></span> </a> </div>';
	var ssbp_sb_social_selected_theme13 = '<div class="mn-social-bottom-c theme12"> <a href=""  class="mn-social-bottom-facebook-theme12 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme12 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a  href="" class="mn-social-bottom-linkedin-theme12 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme12 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a href=""  class="mn-social-bottom-pinterest-theme12 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme14 = '<div class="mn-social-bottom-c theme13"> <a href=""  class="mn-social-bottom-facebook-theme13 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a href=""  class="mn-social-bottom-twitter-theme13 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a href=""  class="mn-social-bottom-linkedin-theme13 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a href=""  class="mn-social-bottom-google-theme13 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a  href="" class="mn-social-bottom-pinterest-theme13 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div>';
	var ssbp_sb_social_selected_theme15 = '<div class="ssbp_social_icon_theme14"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div>';
	var ssbp_sb_social_selected_theme16 = '<div class="ssbp_social_icon_theme15"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div>';
	var ssbp_sb_social_selected_theme17 = '<div class="ssbp_social_icon_theme16"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div>';
	var ssbp_sb_social_selected_theme18 = '<div class="ssbp_social_icon_theme17"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div> ';
	var ssbp_sb_social_selected_theme19 = '<div class="ssbp_social_icon_theme18"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div>';
	var ssbp_sb_social_selected_theme20 = '<div class="ssbp_social_icon_theme19"> <a href="" class="ssbp_facebook ssbp_facebook_icon"><span class="fa fa-facebook"></span></a> <a href="" class="ssbp_twiter ssbp_twitter_icon"><span class="fa fa-twitter"></span></a> <a href="" class="ssbp_google-plus ssbp_googleplus_icon"><span class="fa fa-google-plus"></span></a> <a href="" class="ssbp_linkedin ssbp_linkedin_icon"><span class="fa fa-linkedin"></span></a> <a href="" class="ssbp_pinterest-p ssbp_pinterest_icon"><span class="fa fa-pinterest-p"></span></a> </div>';

	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme1')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme1);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme2')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme2);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme3')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme3);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme4')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme4);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme5')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme5);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme6')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme6);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme7')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme7);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme8')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme8);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme9')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme9);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme10')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme10);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme11')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme11);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme12')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme12);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme13')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme13);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme14')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme14);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme15')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme15);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme16')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme16);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme17')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme17);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme18')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme18);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme19')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme19);
	if($('.ssbp_selected_theme').attr('id') == 'ssbp_sb_social_selected_theme20')
		$('.ssbp_selected_theme').html(ssbp_sb_social_selected_theme20);

var ssbp_floating_theme_selection1 = '<div class="ssbp_floating_theme"><div class="mn-social-bottom-c"> <a class="mn-social-bottom-facebook-theme1 ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme1 ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme1 ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme1 ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme1 ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';

var ssbp_floating_theme_selection2 = '<div class="ssbp_floating_theme"><div class="mn-social-bottom-c theme3 floating-theme3"> <a class="mn-social-bottom-facebook-theme3-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme3-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme3-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme3-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme3-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection3 = '<div class="ssbp_floating_theme"> <div class="mn-social-bottom-c theme4 floating-theme4"> <a class="mn-social-bottom-facebook-theme4-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme4-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme4-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme4-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme4-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection4 = '<div class="ssbp_floating_theme"><div class="mn-social-bottom-c theme5 floating-theme5"> <a class="mn-social-bottom-facebook-theme5-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme5-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme5-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme5-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme5-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection5 = '<div class="ssbp_floating_theme"> <div class="mn-social-bottom-c theme6 floating-theme6"> <a class="mn-social-bottom-facebook-theme6-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme6-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme6-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme6-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme6-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection6 = '<div class="ssbp_floating_theme"> <div class="mn-social-bottom-c theme7 floating-theme7"> <a class="mn-social-bottom-facebook-theme7-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme7-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme7-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme7-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme7-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection7 = '<div class="ssbp_floating_theme"> <div class="mn-social-bottom-c theme8 floating-theme8"> <a class="mn-social-bottom-facebook-theme8-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme8-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme8-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme8-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme8-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection8 = '<div class="ssbp_floating_theme"> <div class="mn-social-bottom-c theme9 floating-theme9"> <a class="mn-social-bottom-facebook-theme9-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme9-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme9-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme9-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme9-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection9 = '<div class="ssbp_floating_theme"><div class="mn-social-bottom-c theme10 floating-theme10"> <a class="mn-social-bottom-facebook-theme10-floating ssbp_facebook_icon"><i class="fa fa-facebook"></i></a> <a class="mn-social-bottom-twitter-theme10-floating ssbp_twitter_icon"><i class="fa fa-twitter"></i></a> <a class="mn-social-bottom-linkedin-theme10-floating ssbp_linkedin_icon"><i class="fa fa-linkedin"></i></a> <a class="mn-social-bottom-google-theme10-floating ssbp_googleplus_icon"><i class="fa fa-google-plus"></i></a> <a class="mn-social-bottom-pinterest-theme10-floating ssbp_pinterest_icon"><i class="fa fa-pinterest-p"></i></a> </div></div>';
var ssbp_floating_theme_selection10 = '<div class="ssbp_floating_theme"><div class="ssbp_buttons2 theme11-floating"> <a href="#" class="btn facebook ssbp_facebook_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-facebook" aria-hidden="true"></i></span> <span class="icon fa fa-facebook"></span> </a> <a href="#" class="btn google-plus ssbp_googleplus_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-google-plus" aria-hidden="true"></i></span> <span class="icon fa fa-google-plus"></span> </a> <a href="#" class="btn twitter ssbp_twitter_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-twitter" aria-hidden="true"></i></span> <span class="icon fa fa-twitter"></span> </a> <a href="#" class="btn linkedin ssbp_linkedin_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-linkedin" aria-hidden="true"></i></span> <span class="icon fa fa-linkedin"></span> </a> <a href="#" class="btn pinterest ssbp_pinterest_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-pinterest-p" aria-hidden="true"></i></span> <span class="icon fa fa-pinterest-p"></span> </a> </div></div>';
var ssbp_floating_theme_selection11 = '<div class="ssbp_floating_theme"><div class="ssbp_buttons2"> <a href="#" class="btn facebook ssbp_facebook_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-facebook" aria-hidden="true"></i></span> <span class="icon fa fa-facebook"></span> </a> <a href="#" class="btn google-plus"> <span class="label"><i id="ssbp_top_fa" class="fa fa-google-plus ssbp_googleplus_icon" aria-hidden="true"></i></span> <span class="icon fa fa-google-plus"></span> </a> <a href="#" class="btn twitter ssbp_twitter_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-twitter" aria-hidden="true"></i></span> <span class="icon fa fa-twitter"></span> </a> <a href="#" class="btn linkedin ssbp_linkedin_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-linkedin" aria-hidden="true"></i></span> <span class="icon fa fa-linkedin"></span> </a> <a href="#" class="btn pinterest ssbp_pinterest_icon"> <span class="label"><i id="ssbp_top_fa" class="fa fa-pinterest-p" aria-hidden="true"></i></span> <span class="icon fa fa-pinterest-p"></span> </a> </div></div>';
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection1')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection1);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection2')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection2);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection3')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection3);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection4')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection4);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection5')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection5);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection6')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection6);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection7')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection7);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection8')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection8);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection9')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection9);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection10')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection10);
	if($('.ssbp_selected_floating_theme').attr('id') == 'ssbp_floating_theme_selection11')
		$('.ssbp_selected_floating_theme').html(ssbp_floating_theme_selection11);

var ssbp_url = window.location;
var ssbp_title = document.title;
	$('.ssbp_facebook_icon').attr('href', 'https://www.facebook.com/sharer/sharer.php?u=' + ssbp_url);
	$('.ssbp_twitter_icon').attr('href', 'https://twitter.com/home?status=' + ssbp_url + ' ' + ssbp_title);
	$('.ssbp_linkedin_icon').attr('href', 'https://www.linkedin.com/shareArticle?mini=true&url=' + ssbp_url);
	$('.ssbp_googleplus_icon').attr('href', 'https://plus.google.com/share?url=' + ssbp_url);
	$('.ssbp_pinterest_icon').attr('href', 'https://pinterest.com/pin/create/link/?url=' + ssbp_url);

	

});


